### ISSUE TITLE
Does not parse unicode pkgver

### ISSUE THREAD

**Issue by simon04** [mikkeloscar/gopkgbuild#10]
This library fails to parse `2.0.0.α.r29.g18fc492` (is used in https://aur.archlinux.org/packages/shaman-git/) into a CompleteVersion. [libalpm/version.c](https://git.archlinux.org/pacman.git/tree/lib/libalpm/version.c#n104) uses `isalnum`, and per `man 3 isalnum`:

```
       isalnum()
              checks for an alphanumeric character; it is equivalent to (isalpha(c) || isdigit(c)).

       isalpha()
              checks for an alphabetic character; in the standard "C" locale, it is equivalent to (isupper(c) ||  islower(c)).   In  some
              locales, there may be additional characters for which isalpha() is true—letters which are neither uppercase nor lowercase.
```

https://github.com/simon04/aur-out-of-date/issues/7

**Comment by Morganamilo** [comment]
Unicode in a version number. Never thought I'd see that.
