### ISSUE TITLE
Parsing too strict?

### ISSUE THREAD

**Issue by Morganamilo** [mikkeloscar/gopkgbuild#11]
The package `qownnotes` has `armv7l` in its arch array. I was going to make a pull request to add support for these arches but as far as I can tell it should be `armv7l`.

Currently parsing the SRCINFO for this package will fail because of the invalid arch. Is it fair to error because of that? `makepkg --printsrcinfo` doesn't care what arch you put in, it just does at it is told.

I think the parsing is a little too strict here and also with the version checking. causing #4 #10 

I could make a pr that just removes the arch check completely but I'd rather run it by you first to see what you think.

Related: Jguer/yay#158

**Comment by mikkeloscar** [comment]
Yeah, lets drop the arch check since it's not so useful!

PR welcome!

Thanks!

**Comment by mikkeloscar** [comment]
Fixed in #13
